### ISSUE TITLE
[M2] Настройки через robin_nano35_cfg.txt

### ISSUE THREAD

**Issue by ange007** [vyacheslav-shubin/mks-robin-nano35-binary#1]
Добрый день.
Планируются ли в новой версии настройки через robin_nano35_cfg.txt? 
Сейчас как я вижу настройка идёт через gcode.

*P.S.: Думаю Вам есть смысл под свой вариант прошивки создать адекватное название репозитория.
Который можно было бы найти поиском.*

**Comment by vyacheslav-shubin** [comment]
Нет. Не планируется, как и любое другое насление от MKS, весь код ui, в том числе графическая библиотека собственный.

**Comment by ange007** [comment]
Я имею ввиду что-то более человеко-понятное. 
Потому как нужно будет очень много доки читать (а Вам писать) чтоб настраивать какие-то определённые параметры _(хотя если будет нормальная настройка в UI + дальнейший бекап на карту, то возможно и так будет норм)_.

**Comment by vyacheslav-shubin** [comment]
Вы ошибаетесь ;)

**Comment by ange007** [comment]
Будем надеяться :)
